name: Python application
on:
  push:
    branches:
      - "master" 

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: lscpu
      - run : free -h