name: Python application
on:
  push:
    branches:
      - "master" 

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run : docker build -t lutan14/cicd/myapp:latest .
      - run : docker login -u lutan14 -p ${{secrets.DOCKER_PASSWORD}}
      - run : docker push lutan14/cicd/myapp:latest