name: Python application
on:
  push:
    branches:
      - "master" 

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: lutan14
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id  : docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lutan14/cicd:v1